name: asi-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - pre-commit
      - ruff
      - black
      - pytest
      - wandb
      - kedro
      - pyarrow
      - pandera
      - great-expectations
      - notebook
      - kedro-datasets
      - kedro-viz
      - autogluon==1.1.0

  - pyyaml
